### ISSUE TITLE
Make the parameters `-p` and `-d` optional if only one project and database are specified in the config

### ISSUE THREAD

**Issue by outdead** [librun/migrago#8]
Сase when the same migrago config is used for different projects is very rare. Most often, the config looks something like this:
```
projects:
  test:
    migrations: 
    - postgres: "migrations/postgresql"
```
In this case, the command is redundant:

      migrago -c config_migrations-local.yaml create -p test -d poetgres -n create_table_test

This command is simpler:

      migrago -c config_migrations-local.yaml create -n create_table_test
